{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import scale\n",
    "from sklearn import metrics\n",
    "from sklearn.cluster import DBSCAN\n",
    "from sklearn import metrics\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.cluster import KMeans\n",
    "from sklearn import linear_model\n",
    "from random import randrange\n",
    "from sklearn import cluster\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn import model_selection\n",
    "\n",
    "dt = pd.read_csv(\"D:/Wahidnew/Final Project/Engineering_graduate_salary.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\890645387.py\", line 2, in <cell line: 2>\n",
      "    dataset = dt.drop([\"ID\", \"DOB\", \"10board\", \"12graduation\", \"12board\", \"CollegeID\", \"CollegeCityID\", \"CollegeCityTier\",\"CollegeState\",\"GraduationYear\"])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pandas\\core\\frame.py\", line 4954, in drop\n",
      "    return super().drop(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pandas\\core\\generic.py\", line 4267, in drop\n",
      "    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pandas\\core\\generic.py\", line 4311, in _drop_axis\n",
      "    new_axis = axis.drop(labels, errors=errors)\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pandas\\core\\indexes\\base.py\", line 6644, in drop\n",
      "    raise KeyError(f\"{list(labels[mask])} not found in axis\")\n",
      "KeyError: \"['ID', 'DOB', '10board', '12graduation', '12board', 'CollegeID', 'CollegeCityID', 'CollegeCityTier', 'CollegeState', 'GraduationYear'] not found in axis\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#Drop nonessential columns\n",
    "dataset = dt.drop([\"ID\", \"DOB\", \"10board\", \"12graduation\", \"12board\", \"CollegeID\", \"CollegeCityID\", \"CollegeCityTier\",\"CollegeState\",\"GraduationYear\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\1001325065.py\", line 3, in <cell line: 3>\n",
      "    dataset['Gender'] = dataset['Gender'].map(d_gender)\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Converting gender value from string to integer\n",
    "d_gender={'f':0, 'm':1}\n",
    "dataset['Gender'] = dataset['Gender'].map(d_gender)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\960789464.py\", line 3, in <cell line: 3>\n",
      "    dataset['Degree'] = dataset['Degree'].map(d_degree)\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Converting Degree value from string to integer\n",
    "d_degree={'B.Tech/B.E.':0, 'MCA':1, 'MCA':2, 'M.Tech/M.E.': 3, 'M.Sc. (Tech.)':4}\n",
    "dataset['Degree'] = dataset['Degree'].map(d_degree)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\1526516279.py\", line 3, in <cell line: 3>\n",
      "    dataset.Degree.median()\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#Update null value in Degree column\n",
    "# dataset.isnull().any()\n",
    "dataset.Degree.median()\n",
    "dataset.Degree = dataset.Degree.fillna(dataset.Degree.median())\n",
    "# dataset.isnull().any()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\886535050.py\", line 46, in <cell line: 46>\n",
      "    dataset['Specialization'] = dataset['Specialization'].map(d_specialization)\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Converting Specialization value from string to integer\n",
    "# dataset['Specialization'].value_counts()\n",
    "d_specialization={'electronics and communication engineering':0, \n",
    "                  'computer science & engineering':1, \n",
    "                  'information technology':2, \n",
    "                  'computer engineering': 3, \n",
    "                  'computer application':4,\n",
    "                  'mechanical engineering':5, \n",
    "                  'electronics and electrical engineering':6, \n",
    "                  'electronics & telecommunications': 7, \n",
    "                  'electrical engineering':8,\n",
    "                  'electronics & instrumentation eng':9, \n",
    "                  'information science engineering':10, \n",
    "                  'electronics and instrumentation engineering': 11, \n",
    "                  'instrumentation and control engineering':12,\n",
    "                  'civil engineering':13, \n",
    "                  'electronics engineering':14, \n",
    "                  'biotechnology': 15, \n",
    "                  'other':16,\n",
    "                  'industrial & production engineering':17, \n",
    "                  'chemical engineering':18, \n",
    "                  'applied electronics and instrumentation': 19, \n",
    "                  'mechanical and automation':20,\n",
    "                  'computer science and technology':21, \n",
    "                  'telecommunication engineering':22, \n",
    "                  'automobile/automotive engineering': 23, \n",
    "                  'instrumentation engineering':24,\n",
    "                  'electronics and computer engineering':25, \n",
    "                  'mechatronics':26, \n",
    "                  'aeronautical engineering': 27, \n",
    "                  'industrial engineering':28,\n",
    "                  'biomedical engineering':29, \n",
    "                  'metallurgical engineering':30, \n",
    "                  'ceramic engineering': 31, \n",
    "                  'embedded systems technology':32,\n",
    "                  'computer and communication engineering':33, \n",
    "                  'electronics':34, \n",
    "                  'information science': 35, \n",
    "                  'control and instrumentation engineering':36,\n",
    "                  'industrial & management engineering':37, \n",
    "                  'mechanical & production engineering':38, \n",
    "                  'computer networking': 39, \n",
    "                  'electrical and power engineering':40,\n",
    "                  'information & communication technology':41\n",
    "                 }\n",
    "dataset['Specialization'] = dataset['Specialization'].map(d_specialization)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\2410214830.py\", line 1, in <cell line: 1>\n",
      "    dataset.head()\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "dataset.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\2140274932.py\", line 1, in <cell line: 1>\n",
      "    print(\"Average Salary of male: \",int(dataset.loc[dataset['Gender'] == 1, 'Salary'].mean()))\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "print(\"Average Salary of male: \",int(dataset.loc[dataset['Gender'] == 1, 'Salary'].mean()))\n",
    "print(\"Average Salary of female: \",int(dataset.loc[dataset['Gender'] == 0, 'Salary'].mean()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\359391351.py\", line 2, in <cell line: 2>\n",
      "    gender = dataset[\"Gender\"]\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#Gender(Male - Female ratio)\n",
    "gender = dataset[\"Gender\"]\n",
    "male  = (len(gender[dataset[\"Gender\"] == 1]))\n",
    "female  = (len(gender[dataset[\"Gender\"] == 0]))\n",
    "sizes = [male, female]\n",
    "labels = 'Male', 'Female'\n",
    "explode = (0, 0.1)\n",
    "plt.pie (sizes, labels=labels, explode=explode, shadow=True, autopct='%1.0f%%', pctdistance=0.5, labeldistance=1.2)\n",
    "plt.axis('equal')\n",
    "plt.title(\"Candidate gender: Male and Female\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\2948396470.py\", line 3, in <cell line: 3>\n",
      "    male   = int(dataset.loc[dataset['Gender'] == 1, 'Salary'].mean())\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Average salary of male and female\n",
    "# bar = dataset.groupby('Gender', as_index=False).Salary.mean().set_index('Gender')\n",
    "male   = int(dataset.loc[dataset['Gender'] == 1, 'Salary'].mean())\n",
    "female = int(dataset.loc[dataset['Gender'] == 0, 'Salary'].mean())\n",
    "figc = plt.figure()\n",
    "c = figc.add_axes([0,0,1,1])\n",
    "lables = ['Male', 'Female']\n",
    "salary_package = [male, female]\n",
    "c.bar(lables,salary_package, width=0.4, color=['blue', 'orange'])\n",
    "plt.title('Male-Female average salary packages comparison')\n",
    "plt.xlabel('Gender')\n",
    "plt.ylabel('Average salary package')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\4040941224.py\", line 2, in <cell line: 2>\n",
      "    above_90_a  = int(dataset.loc[dataset['10percentage'] > 90, 'Salary'].mean())\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# 10th, 12th Standard and University GPA student marks(%) counts and their salary package\n",
    "above_90_a  = int(dataset.loc[dataset['10percentage'] > 90, 'Salary'].mean())\n",
    "bet_90_70_a = int(dataset.loc[((dataset['10percentage'] < 90) & (dataset['10percentage'] > 70)), 'Salary'].mean())\n",
    "bet_70_50_a = int(dataset.loc[((dataset['10percentage'] < 70) & (dataset['10percentage'] > 50)), 'Salary'].mean())\n",
    "bel_50_a = int(dataset.loc[dataset['10percentage'] < 50, 'Salary'].mean())\n",
    "\n",
    "above_90_b  = int(dataset.loc[dataset['12percentage'] > 90, 'Salary'].mean())\n",
    "bet_90_70_b = int(dataset.loc[((dataset['12percentage'] < 90) & (dataset['12percentage'] > 70)), 'Salary'].mean())\n",
    "bet_70_50_b = int(dataset.loc[((dataset['12percentage'] < 70) & (dataset['12percentage'] > 50)), 'Salary'].mean())\n",
    "bel_50_b = int(dataset.loc[dataset['12percentage'] < 50, 'Salary'].mean())\n",
    "\n",
    "above_90_c  = int(dataset.loc[dataset['collegeGPA'] > 90, 'Salary'].mean())\n",
    "bet_90_70_c = int(dataset.loc[((dataset['collegeGPA'] < 90) & (dataset['collegeGPA'] > 70)), 'Salary'].mean())\n",
    "bet_70_50_c = int(dataset.loc[((dataset['collegeGPA'] < 70) & (dataset['collegeGPA'] > 50)), 'Salary'].mean())\n",
    "bel_50_c = int(dataset.loc[dataset['collegeGPA'] < 50, 'Salary'].mean())\n",
    "\n",
    "a = [above_90_a, bet_90_70_a, bet_70_50_a, bel_50_a]\n",
    "b = [above_90_b, bet_90_70_b, bet_70_50_b, bel_50_b]\n",
    "c = [above_90_c, bet_90_70_c, bet_70_50_c, bel_50_c]\n",
    "X = np.arange(4)\n",
    "width = 0.2\n",
    "fig, ax = plt.subplots()\n",
    "ax.bar(X, a, width, color='blue', label='Class 10')\n",
    "ax.bar(X+width, b, width, color='orange', label='Class 12')\n",
    "ax.bar(X+width+width, c, width, color='green', label='College GPA')\n",
    "ax.legend(loc=\"upper right\")\n",
    "ax.set_xticks(X + width / 2)\n",
    "ax.set_xticklabels(('Above 90', '90% to 70%', '70% to 50%', 'Below 50%'))\n",
    "plt.ylabel('Annual salary')\n",
    "plt.xlabel('Marks in percentage')\n",
    "# plt.title('Class 10 and 12 marks salary package')\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\4180695039.py\", line 2, in <cell line: 2>\n",
      "    tier = dataset[\"CollegeTier\"]\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# College Tier\n",
    "tier = dataset[\"CollegeTier\"]\n",
    "tier1  = (len(tier[dataset[\"CollegeTier\"] == 1]))\n",
    "tier2  = (len(tier[dataset[\"CollegeTier\"] == 2]))\n",
    "sizes = [tier2, tier1,]\n",
    "labels = 'Tier 2', 'Tier 1'\n",
    "explode = (0, 0.1)\n",
    "plt.pie (sizes, labels=labels, explode=explode, shadow=True, autopct='%1.0f%%', pctdistance=0.5, labeldistance=1.2)\n",
    "plt.axis('equal')\n",
    "plt.title(\"College tier\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\371692334.py\", line 2, in <cell line: 2>\n",
      "    tier1_sal   = int(dataset.loc[dataset['CollegeTier'] == 1, 'Salary'].mean())\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Find which tier college students get maximum salary(average) package\n",
    "tier1_sal   = int(dataset.loc[dataset['CollegeTier'] == 1, 'Salary'].mean())\n",
    "tier2_sal = int(dataset.loc[dataset['CollegeTier'] == 2, 'Salary'].mean())\n",
    "figc = plt.figure()\n",
    "c = figc.add_axes([0,0,1,1])\n",
    "lables = ['Tier 1', 'Tier 2']\n",
    "salary_package = [tier1_sal, tier2_sal]\n",
    "c.bar(lables,salary_package, width=0.4, color=['blue', 'orange'])\n",
    "# plt.title('College tier average salary packages comparison')\n",
    "plt.xlabel('College tier')\n",
    "plt.ylabel('Average salary package')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# print(dataset.loc[dataset['CollegeTier'] == 1, 'Salary'].mean()) #Avg. salary of Tier 1 college student\n",
    "# print((len(tier[dataset[\"CollegeTier\"] == 2]))) #Avg. salary of Tier 2 college student\n",
    "#AMCAT English marks and salary package comparisons\n",
    "# plt.scatter(dataset['English'], dataset['Salary'], alpha=0.5)\n",
    "# plt.xlabel('AMCAT English marks')\n",
    "# plt.ylabel('Average salary package(lakhs)')\n",
    "# plt.show()\n",
    "#AMCAT Logical marks and salary package comparisons\n",
    "# plt.scatter(dataset['Logical'], dataset['Salary'], alpha=0.5)\n",
    "# plt.xlabel('AMCAT Logical marks')\n",
    "# plt.ylabel('Average salary package(lakhs)')\n",
    "# plt.show()\n",
    "#AMCAT Quant marks and salary package comparisons\n",
    "# plt.scatter(dataset['Quant'], dataset['Salary'], alpha=0.5)\n",
    "# plt.xlabel('AMCAT Quant marks')\n",
    "# plt.ylabel('Average salary package(lakhs)')\n",
    "# plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\3026544093.py\", line 2, in <cell line: 2>\n",
      "    amcat_score_dataset = dataset.copy()\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#AMCAT modules marks and salary package comparisons\n",
    "amcat_score_dataset = dataset.copy()\n",
    "amcat_score_dataset = amcat_score_dataset.drop(['Gender','ComputerProgramming','ElectronicsAndSemicon','ComputerScience','MechanicalEngg','ElectricalEngg','TelecomEngg','CivilEngg', '10percentage','12percentage','CollegeTier','Degree','Specialization','collegeGPA'], axis=1)\n",
    "x = amcat_score_dataset.corr()\n",
    "sns.heatmap(x, annot=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\3422500846.py\", line 7, in <cell line: 7>\n",
      "    sns.heatmap(dataset.corr(), ax=ax, annot=True)\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAABBkAAAKvCAYAAAAvPBegAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAcL0lEQVR4nO3dX6jn913n8de7GaNQawtmFiSJJuB062xXaPeQ7dILC+0uSS4yF4okULQSmpuNuGsRIkqVeFXLKgjxT8RSLdgYeyEDRnKhkYKYkil1Q5MSGaLbTBQy1mxuio3Z/ezFOS7HcWbOz8nrzPlN5/GAgd/3+/v8fr/3zYcz85zv73tmrRUAAACAN+stRz0AAAAA8M1BZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACoOjAwz86mZeWVmvnyJ52dmfmVmzs7MszPz3v6YAAAAwLbb5EqGTye58zLP35XkxN6fB5L82psfCwAAALjWHBgZ1lqfT/L3l1lyKsnvrF1PJ3nHzHxXa0AAAADg2nCs8B43J3lp3/G5vXN/e+HCmXkgu1c75K1vfet/eNe73lX4eAAAAKDli1/84t+ttY5fyWsbkWFja61HkzyaJDs7O+vMmTNX8+MBAACAA8zM/7rS1zZ+u8TLSW7dd3zL3jkAAADgOtKIDKeT/Mjeb5l4X5LX1lr/4qsSAAAAwDe3A78uMTOfTfKBJDfNzLkkP5fkW5JkrfXrSZ5IcneSs0m+nuTHDmtYAAAAYHsdGBnWWvcd8PxK8l9rEwEAAADXpMbXJQAAAABEBgAAAKBDZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBio8gwM3fOzAszc3ZmHrrI8989M0/NzJdm5tmZubs/KgAAALDNDowMM3NDkkeS3JXkZJL7ZubkBct+Nsnja633JLk3ya+2BwUAAAC22yZXMtyR5Oxa68W11utJHkty6oI1K8l37D1+e5K/6Y0IAAAAXAs2iQw3J3lp3/G5vXP7/XySD8/MuSRPJPnxi73RzDwwM2dm5sz58+evYFwAAABgW7Vu/Hhfkk+vtW5JcneSz8zMv3jvtdaja62dtdbO8ePHSx8NAAAAbINNIsPLSW7dd3zL3rn97k/yeJKstf48ybcluakxIAAAAHBt2CQyPJPkxMzcPjM3ZvfGjqcvWPPVJB9Mkpn5vuxGBt+HAAAAgOvIgZFhrfVGkgeTPJnkK9n9LRLPzczDM3PP3rKPJfnozPzPJJ9N8pG11jqsoQEAAIDtc2yTRWutJ7J7Q8f95z6+7/HzSd7fHQ0AAAC4lrRu/AgAAABc50QGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKjaKDDNz58y8MDNnZ+ahS6z54Zl5fmaem5nf7Y4JAAAAbLtjBy2YmRuSPJLkPyc5l+SZmTm91np+35oTSX46yfvXWq/OzL85rIEBAACA7bTJlQx3JDm71npxrfV6kseSnLpgzUeTPLLWejVJ1lqvdMcEAAAAtt0mkeHmJC/tOz63d26/dyZ558z82cw8PTN3XuyNZuaBmTkzM2fOnz9/ZRMDAAAAW6l148djSU4k+UCS+5L85sy848JFa61H11o7a62d48ePlz4aAAAA2AabRIaXk9y67/iWvXP7nUtyeq31j2utv0ryl9mNDgAAAMB1YpPI8EySEzNz+8zcmOTeJKcvWPMH2b2KITNzU3a/PvFib0wAAABg2x0YGdZabyR5MMmTSb6S5PG11nMz8/DM3LO37MkkX5uZ55M8leSn1lpfO6yhAQAAgO0za60j+eCdnZ115syZI/lsAAAA4OJm5otrrZ0reW3rxo8AAADAdU5kAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACo2igwzc+fMvDAzZ2fmocus+8GZWTOz0xsRAAAAuBYcGBlm5oYkjyS5K8nJJPfNzMmLrHtbkp9I8oX2kAAAAMD22+RKhjuSnF1rvbjWej3JY0lOXWTdLyT5RJJ/KM4HAAAAXCM2iQw3J3lp3/G5vXP/38y8N8mta60/vNwbzcwDM3NmZs6cP3/+Xz0sAAAAsL3e9I0fZ+YtSX4pyccOWrvWenSttbPW2jl+/Pib/WgAAABgi2wSGV5Ocuu+41v2zv2TtyV5d5I/nZm/TvK+JKfd/BEAAACuL5tEhmeSnJiZ22fmxiT3Jjn9T0+utV5ba9201rptrXVbkqeT3LPWOnMoEwMAAABb6cDIsNZ6I8mDSZ5M8pUkj6+1npuZh2fmnsMeEAAAALg2HNtk0VrriSRPXHDu45dY+4E3PxYAAABwrXnTN34EAAAASEQGAAAAoERkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKkQGAAAAoEJkAAAAACpEBgAAAKBCZAAAAAAqRAYAAACgQmQAAAAAKjaKDDNz58y8MDNnZ+ahizz/kzPz/Mw8OzN/PDPf0x8VAAAA2GYHRoaZuSHJI0nuSnIyyX0zc/KCZV9KsrPW+v4kn0vyi+1BAQAAgO22yZUMdyQ5u9Z6ca31epLHkpzav2Ct9dRa6+t7h08nuaU7JgAAALDtNokMNyd5ad/xub1zl3J/kj+62BMz88DMnJmZM+fPn998SgAAAGDrVW/8ODMfTrKT5JMXe36t9ehaa2ettXP8+PHmRwMAAABH7NgGa15Ocuu+41v2zv0zM/OhJD+T5AfWWt/ojAcAAABcKza5kuGZJCdm5vaZuTHJvUlO718wM+9J8htJ7llrvdIfEwAAANh2B0aGtdYbSR5M8mSSryR5fK313Mw8PDP37C37ZJJvT/L7M/MXM3P6Em8HAAAAfJPa5OsSWWs9keSJC859fN/jD5XnAgAAAK4x1Rs/AgAAANcvkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACoEBkAAACACpEBAAAAqBAZAAAAgAqRAQAAAKgQGQAAAIAKkQEAAACo2CgyzMydM/PCzJydmYcu8vy3zszv7T3/hZm5rT4pAAAAsNUOjAwzc0OSR5LcleRkkvtm5uQFy+5P8upa63uT/HKST7QHBQAAALbbJlcy3JHk7FrrxbXW60keS3LqgjWnkvz23uPPJfngzExvTAAAAGDbHdtgzc1JXtp3fC7Jf7zUmrXWGzPzWpLvTPJ3+xfNzANJHtg7/MbMfPlKhobrxE25YA8B/4w9Apdnj8Dl2SNwaf/2Sl+4SWSoWWs9muTRJJmZM2utnav5+XAtsUfg8uwRuDx7BC7PHoFLm5kzV/raTb4u8XKSW/cd37J37qJrZuZYkrcn+dqVDgUAAABcezaJDM8kOTEzt8/MjUnuTXL6gjWnk/zo3uMfSvIna63VGxMAAADYdgd+XWLvHgsPJnkyyQ1JPrXWem5mHk5yZq11OslvJfnMzJxN8vfZDREHefRNzA3XA3sELs8egcuzR+Dy7BG4tCveH+OCAwAAAKBhk69LAAAAABxIZAAAAAAqDj0yzMydM/PCzJydmYcu8vy3zszv7T3/hZm57bBngm2ywR75yZl5fmaenZk/npnvOYo54agctEf2rfvBmVkz49eRcd3YZH/MzA/v/Rx5bmZ+92rPCEdpg79nfffMPDUzX9r7u9bdRzEnHJWZ+dTMvDIzX77E8zMzv7K3h56dmfce9J6HGhlm5oYkjyS5K8nJJPfNzMkLlt2f5NW11vcm+eUknzjMmWCbbLhHvpRkZ631/Uk+l+QXr+6UcHQ23COZmbcl+YkkX7i6E8LR2WR/zMyJJD+d5P1rrX+X5L9d7TnhqGz4M+Rnkzy+1npPdm9e/6tXd0o4cp9Ocudlnr8ryYm9Pw8k+bWD3vCwr2S4I8nZtdaLa63XkzyW5NQFa04l+e29x59L8sGZmUOeC7bFgXtkrfXUWuvre4dPJ7nlKs8IR2mTnyNJ8gvZjdT/cDWHgyO2yf74aJJH1lqvJsla65WrPCMcpU32yEryHXuP357kb67ifHDk1lqfz+5viLyUU0l+Z+16Osk7Zua7Lveehx0Zbk7y0r7jc3vnLrpmrfVGkteSfOchzwXbYpM9st/9Sf7oUCeC7XLgHtm7bO/WtdYfXs3BYAts8jPknUneOTN/NjNPz8zl/rcKvtlsskd+PsmHZ+ZckieS/PjVGQ2uGf/af6/k2KGOA9TMzIeT7CT5gaOeBbbFzLwlyS8l+cgRjwLb6lh2L3H9QHavhPv8zPz7tdb/PsqhYIvcl+TTa63/MTP/KclnZubda63/e9SDwbXqsK9keDnJrfuOb9k7d9E1M3Msu5cpfe2Q54Jtsckeycx8KMnPJLlnrfWNqzQbbIOD9sjbkrw7yZ/OzF8neV+S027+yHVik58h55KcXmv941rrr5L8ZXajA1wPNtkj9yd5PEnWWn+e5NuS3HRVpoNrw0b/XtnvsCPDM0lOzMztM3Njdm+mcvqCNaeT/Oje4x9K8idrrXXIc8G2OHCPzMx7kvxGdgOD79JyvbnsHllrvbbWummtddta67bs3rfknrXWmaMZF66qTf6e9QfZvYohM3NTdr8+8eJVnBGO0iZ75KtJPpgkM/N92Y0M56/qlLDdTif5kb3fMvG+JK+ttf72ci841K9LrLXemJkHkzyZ5IYkn1prPTczDyc5s9Y6neS3sntZ0tns3nDi3sOcCbbJhnvkk0m+Pcnv790T9atrrXuObGi4ijbcI3Bd2nB/PJnkv8zM80n+T5KfWmu5YpTrwoZ75GNJfnNm/nt2bwL5Ef/hyfVkZj6b3Rh90969SX4uybckyVrr17N7r5K7k5xN8vUkP3bge9pDAAAAQMNhf10CAAAAuE6IDAAAAECFyAAAAABUiAwAAABAhcgAAAAAVIgMAAAAQIXIAAAAAFT8P3pTqEwOs8arAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 1296x864 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# amcat_score_dataset = dataset.copy()\n",
    "# amcat_score_dataset = amcat_score_dataset.drop(['Gender','ComputerProgramming','ElectronicsAndSemicon','ComputerScience','MechanicalEngg','ElectricalEngg','TelecomEngg','CivilEngg', '10percentage','12percentage','CollegeTier','Degree','Specialization','collegeGPA'], axis=1)\n",
    "# x = dataset.corr()\n",
    "# sns.heatmap(x)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(18,12))\n",
    "sns.heatmap(dataset.corr(), ax=ax, annot=True)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\2410214830.py\", line 1, in <cell line: 1>\n",
      "    dataset.head()\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "dataset.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\3817081189.py\", line 3, in <cell line: 3>\n",
      "    X = dataset.values[:, 8:10] #Logical and Quant marks\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#Unsupervised Analysis\n",
    "# Scaling data\n",
    "X = dataset.values[:, 8:10] #Logical and Quant marks\n",
    "Y = dataset.values[:,23] #Salary\n",
    "scaled_data = scale(X)   #scaling X : Logical and Quant marks\n",
    "# Y = scale(Y)\n",
    "# print(Y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\2802642714.py\", line 2, in <cell line: 2>\n",
      "    n_samples, n_features = scaled_data.shape\n",
      "NameError: name 'scaled_data' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# K-means clustering 2 to 30\n",
    "n_samples, n_features = scaled_data.shape\n",
    "\n",
    "sillhoute = []\n",
    "completenes = []\n",
    "homogeneity = []\n",
    "\n",
    "inertia = []\n",
    "\n",
    "n_digits = len(np.unique(Y))\n",
    "Y2 = LabelEncoder().fit_transform(Y)\n",
    "for k in range(2, 30):\n",
    " kmeans = cluster.KMeans(n_clusters=k)\n",
    " y_fit = kmeans.fit_predict(scaled_data)\n",
    "#  print(k)\n",
    "#  print(y_fit)\n",
    "#  print(metrics.silhouette_score(scaled_data, kmeans.labels_))\n",
    "#  print(metrics.completeness_score(Y2, kmeans.labels_))\n",
    "#  print(metrics.homogeneity_score(Y2, kmeans.labels_))\n",
    "#  print(\"   \")\n",
    " sillhoute.append(metrics.silhouette_score(scaled_data, kmeans.labels_))\n",
    " completenes.append(metrics.completeness_score(Y2, kmeans.labels_))\n",
    " homogeneity.append(metrics.homogeneity_score(Y2, kmeans.labels_))\n",
    " inertia.append(kmeans.inertia_)\n",
    "print(\"K-means algorithm processed\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\366178379.py\", line 3, in <cell line: 3>\n",
      "    plt.plot(sillhoute, color='green', label='Sillhoute score')\n",
      "NameError: name 'sillhoute' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Performance of K-means cluster\n",
    "# plt.plot(sillhoute,'g*', completenes, 'ro', homogeneity, '--')\n",
    "plt.plot(sillhoute, color='green', label='Sillhoute score')\n",
    "plt.plot(completenes, color='red', label='Completenes score')\n",
    "plt.plot(homogeneity, color='blue', label='Homogeneity score')\n",
    "plt.legend(bbox_to_anchor=(1, 0.9), loc='center left', ncol=1)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\3932034834.py\", line 2, in <cell line: 2>\n",
      "    plt.plot(wcss, marker='x')\n",
      "NameError: name 'wcss' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#Determine the number of clusters\n",
    "plt.plot(wcss, marker='x')\n",
    "plt.title('The Elbow Method')\n",
    "plt.xlabel('Number of Clusters')\n",
    "plt.ylabel('Inertia')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\517133574.py\", line 2, in <cell line: 2>\n",
      "    kmeans = cluster.KMeans(n_clusters=6).fit(scaled_data)\n",
      "NameError: name 'scaled_data' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#6 clusters \n",
    "kmeans = cluster.KMeans(n_clusters=6).fit(scaled_data)\n",
    "# y_fit = kmeans.fit(scaled_data)\n",
    "dataset['labels'] = kmeans.labels_\n",
    "# print(kmeans.labels_)\n",
    "# kmeans.cluster_centers_\n",
    "print(\"Silhouette score\", metrics.silhouette_score(scaled_data, kmeans.labels_))\n",
    "print(\"Homogeneity score\", metrics.homogeneity_score(Y2, kmeans.labels_))\n",
    "print(\"Completeness score\", metrics.completeness_score(Y2, kmeans.labels_))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\4074764200.py\", line 1, in <cell line: 1>\n",
      "    kml = kmeans.labels_\n",
      "NameError: name 'kmeans' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "kml = kmeans.labels_\n",
    "print(np.unique(kml))\n",
    "print(\"Number of clusters: \",len(np.unique(kml)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\2516109991.py\", line 2, in <cell line: 2>\n",
      "    plt.scatter(X[:,0],X[:,1], c=kmeans.labels_, cmap='rainbow')\n",
      "NameError: name 'X' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#cluster visulization\n",
    "plt.scatter(X[:,0],X[:,1], c=kmeans.labels_, cmap='rainbow')\n",
    "plt.xlabel('Logical marks')\n",
    "plt.ylabel('Quant marks')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\2370125228.py\", line 4, in <cell line: 4>\n",
      "    logical_df = dataset.drop(['Gender','10percentage','12percentage','CollegeTier','Degree','Specialization','collegeGPA','English','Quant','Domain','ComputerProgramming','ElectronicsAndSemicon','ComputerScience','MechanicalEngg','ElectricalEngg','TelecomEngg','CivilEngg','conscientiousness','agreeableness','extraversion','nueroticism','openess_to_experience','Salary', 'labels'],axis='columns')\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#Supervised Analysis\n",
    "##Single value linear regressiona\n",
    "##Making dataset for single value supervised analysis\n",
    "logical_df = dataset.drop(['Gender','10percentage','12percentage','CollegeTier','Degree','Specialization','collegeGPA','English','Quant','Domain','ComputerProgramming','ElectronicsAndSemicon','ComputerScience','MechanicalEngg','ElectricalEngg','TelecomEngg','CivilEngg','conscientiousness','agreeableness','extraversion','nueroticism','openess_to_experience','Salary', 'labels'],axis='columns')\n",
    "quant_df = dataset.drop(['Gender','CollegeTier', '10percentage', '12percentage','Degree','Specialization','collegeGPA','English','Logical','Domain','ComputerProgramming','ElectronicsAndSemicon','ComputerScience','MechanicalEngg','ElectricalEngg','TelecomEngg','CivilEngg','conscientiousness','agreeableness','extraversion','nueroticism','openess_to_experience','Salary', 'labels'],axis='columns')\n",
    "salary = dataset.Salary\n",
    "# dataset.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\3779633949.py\", line 3, in <cell line: 3>\n",
      "    reg.fit(logical_df,salary)\n",
      "NameError: name 'logical_df' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "#Salary prediction based on Logical marks\n",
    "reg = linear_model.LinearRegression()\n",
    "reg.fit(logical_df,salary)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\736079045.py\", line 6, in <cell line: 6>\n",
      "    ranadom_df = dataset.sample(n=5)\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Annual salary actual and prediction comparison for 5 random students with their AMCAT Logical marks from dataset.\n",
    "logical_marks = []\n",
    "actual_salary = []\n",
    "predicted_salary = []\n",
    "\n",
    "ranadom_df = dataset.sample(n=5)\n",
    "for i, row in ranadom_df.iterrows():\n",
    "    logical_marks.append(row['Logical'])\n",
    "    actual_salary.append(row['Salary'])\n",
    "    predicted_salary.append((reg.predict([[row['Logical']]])).astype(int)[0])\n",
    "\n",
    "\n",
    "X = np.arange(5)\n",
    "width = 0.2\n",
    "salary_legend=['Actual Salary','Predicted Salary']\n",
    "fig, ax = plt.subplots()\n",
    "ax.bar(X, actual_salary, width, color='blue')\n",
    "ax.bar(X+width, predicted_salary, width, color='y')\n",
    "ax.set_xticks(X + width / 2)\n",
    "ax.set_xticklabels(logical_marks)\n",
    "plt.xlabel(\"Logical module marks\")\n",
    "plt.ylabel('Salary')\n",
    "# plt.title('Actual and Predected Salary')\n",
    "plt.legend(salary_legend, bbox_to_anchor=(1, 0.9), loc='center left', ncol=1)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\807234722.py\", line 6, in <cell line: 6>\n",
      "    ranadom_df = dataset.sample(n=5)\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Annual actual salary and predicted comparison for 5 random students with their AMCAT Quantitive marks from dataset.\n",
    "quant = []\n",
    "actual_salary = []\n",
    "predicted_salary = []\n",
    "\n",
    "ranadom_df = dataset.sample(n=5)\n",
    "for i, row in ranadom_df.iterrows():\n",
    "    quant.append(row['Quant'])\n",
    "    actual_salary.append(row['Salary'])\n",
    "    predicted_salary.append((reg.predict([[row['Quant']]])).astype(int)[0])\n",
    "    \n",
    "\n",
    "X = np.arange(5)\n",
    "width = 0.2\n",
    "salary_legend=['Actual Salary','Predicted Salary']\n",
    "fig, ax = plt.subplots()\n",
    "ax.bar(X, actual_salary, width, color='blue')\n",
    "ax.bar(X+width, predicted_salary, width, color='y')\n",
    "ax.set_xticks(X + width / 2)\n",
    "ax.set_xticklabels(quant)\n",
    "plt.xlabel(\"Quant\")\n",
    "plt.ylabel('Salary')\n",
    "plt.title('Actual and Predected Salary')\n",
    "plt.legend(salary_legend, bbox_to_anchor=(1, 0.9), loc='center left', ncol=1)\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\138874630.py\", line 2, in <cell line: 2>\n",
      "    multi_reg_df = dataset.drop(['Gender','Degree','CollegeTier','Specialization','ComputerProgramming','ElectronicsAndSemicon','ComputerScience','MechanicalEngg','ElectricalEngg'])\n",
      "NameError: name 'dataset' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "##Multiple value linear regression\n",
    "multi_reg_df = dataset.drop(['Gender','Degree','CollegeTier','Specialization','ComputerProgramming','ElectronicsAndSemicon','ComputerScience','MechanicalEngg','ElectricalEngg'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\138822635.py\", line 3, in <cell line: 3>\n",
      "    reg.fit(multi_reg_df,dataset.Salary)\n",
      "NameError: name 'multi_reg_df' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# multi_reg_df\n",
    "reg = linear_model.LinearRegression()\n",
    "reg.fit(multi_reg_df,dataset.Salary)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\4148006506.py\", line 1, in <cell line: 1>\n",
      "    LinearRegression()\n",
      "NameError: name 'LinearRegression' is not defined\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "LinearRegression()\n",
    "# Annual actual salary and predicted comparison for 5 random students with multiple columns from dataset.\n",
    "ranadom_df = dataset.sample(n=5)\n",
    "candidate = []\n",
    "actual_salary = []\n",
    "predicted_salary = []\n",
    "count = 1\n",
    "\n",
    "\n",
    "for i, row in ranadom_df.iterrows():\n",
    "    val = \"Candidate \"+str(count)\n",
    "    candidate.append(val)\n",
    "    actual_salary.append(row['Salary'])\n",
    "    pred_salary = reg.predict([[row['10percentage'], row['12percentage'], row['collegeGPA'], row['English'], row['Logical'], row['Quant'], row['Domain']]])\n",
    "    predicted_salary.append(pred_salary.astype(int)[0])\n",
    "    count+= 1\n",
    "      \n",
    "X = np.arange(5)\n",
    "width = 0.2\n",
    "salary_legend=['Actual Salary','Predicted Salary']\n",
    "fig, ax = plt.subplots()\n",
    "ax.bar(X, actual_salary, width, color='blue')\n",
    "ax.bar(X+width, predicted_salary, width, color='y')\n",
    "ax.set_xticks(X + width / 2)\n",
    "ax.set_xticklabels(candidate)\n",
    "# plt.xlabel(\"Quant\")\n",
    "plt.ylabel('Salary')\n",
    "plt.title('Actual and Predected Salary')\n",
    "plt.legend(salary_legend, bbox_to_anchor=(1, 0.9), loc='center left', ncol=1)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 3398, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19580\\1913756919.py\", line 4, in <cell line: 3>\n",
      "    j = actual_salary[x] - predicted_salary[0]\n",
      "IndexError: list index out of range\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\interactiveshell.py\", line 1993, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 799, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\core\\ultratb.py\", line 845, in get_records\n",
      "    style = stack_data.style_with_executing_node(style, \"bg:ansiyellow\")\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\stack_data\\core.py\", line 424, in style_with_executing_node\n",
      "    class NewStyle(style):\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 91, in __new__\n",
      "    ndef[4] = colorformat(styledef[3:])\n",
      "  File \"C:\\Users\\hp\\AppData\\Roaming\\Python\\Python310\\site-packages\\pygments\\style.py\", line 58, in colorformat\n",
      "    assert False, \"wrong color format %r\" % text\n",
      "AssertionError: wrong color format 'ansiyellow'\n"
     ]
    }
   ],
   "source": [
    "# Mean Absolute Error (MAE)\n",
    "mae = 0\n",
    "for x in range(5):\n",
    "  j = actual_salary[x] - predicted_salary[0]\n",
    "  if j < 0:\n",
    "    j = j * (-1)\n",
    "  \n",
    "  mae = mae + j\n",
    "\n",
    "print(\"Predictions are off by approximately :INR\",mae/5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Predictions are off by approximately :INR 77806.6\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.6 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "63963b3f4c440940f0b94a3100916033a226cb4f45979123153792d60aa56d6a"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
